-- Additive provider-integration and normalized-attendance foundation.
-- Apply after Seed_DataBase.sql and Seed_DataBase2.sql, before deploying code
-- that reads ClassroomMemberships. This file is not run by the application.
BEGIN;

CREATE TABLE IF NOT EXISTS schools (
    id text PRIMARY KEY,
    name text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO schools (id, name) VALUES ('local-default', 'Attendance Quest School')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS schoolid text;
UPDATE classrooms SET schoolid = 'local-default' WHERE schoolid IS NULL OR schoolid = '';
ALTER TABLE classrooms ALTER COLUMN schoolid SET DEFAULT 'local-default';
ALTER TABLE classrooms ALTER COLUMN schoolid SET NOT NULL;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_classrooms_school') THEN
        ALTER TABLE classrooms ADD CONSTRAINT fk_classrooms_school
            FOREIGN KEY (schoolid) REFERENCES schools(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS classroommemberships (
    classroomid text NOT NULL REFERENCES classrooms(id) ON UPDATE CASCADE,
    userid text NOT NULL,
    membershiprole text NOT NULL CHECK (membershiprole IN ('student', 'teacher')),
    isprimary boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    source text NOT NULL DEFAULT 'local' CHECK (source IN ('local', 'imported')),
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (classroomid, userid, membershiprole)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_classroommemberships_primary_student
    ON classroommemberships (userid)
    WHERE membershiprole = 'student' AND isprimary AND active;

INSERT INTO classroommemberships (classroomid, userid, membershiprole, isprimary)
SELECT cs.classroomid, cs.studentid, 'student', COALESCE(u.classroomid = cs.classroomid, false)
FROM classroomstudents cs
JOIN classrooms c ON c.id = cs.classroomid
LEFT JOIN users u ON u.userid = cs.studentid
ON CONFLICT (classroomid, userid, membershiprole) DO NOTHING;
INSERT INTO classroommemberships (classroomid, userid, membershiprole, isprimary)
SELECT c.id, c.teacherid, 'teacher', true
FROM classrooms c
WHERE COALESCE(c.teacherid, '') <> ''
ON CONFLICT (classroomid, userid, membershiprole) DO NOTHING;

CREATE TABLE IF NOT EXISTS integrationconnections (
    integrationconnectionid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    providerkind text NOT NULL,
    connectionrole text NOT NULL CHECK (connectionrole IN ('roster_source', 'attendance_destination')),
    displayname text NOT NULL,
    status text NOT NULL DEFAULT 'disabled' CHECK (status IN ('active', 'disabled', 'error')),
    configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
    credentialciphertext bytea,
    credentialnonce bytea,
    encryptionversion integer,
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((credentialciphertext IS NULL AND credentialnonce IS NULL AND encryptionversion IS NULL)
        OR (credentialciphertext IS NOT NULL AND credentialnonce IS NOT NULL AND encryptionversion IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS externalentitymappings (
    externalentitymappingid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integrationconnectionid bigint NOT NULL REFERENCES integrationconnections(integrationconnectionid),
    entitykind text NOT NULL CHECK (entitykind IN ('school', 'classroom', 'user')),
    externalid text NOT NULL,
    localid text NOT NULL,
    sisid text,
    active boolean NOT NULL DEFAULT true,
    lastseenat timestamptz,
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (integrationconnectionid, entitykind, externalid),
    UNIQUE (integrationconnectionid, entitykind, localid)
);

CREATE TABLE IF NOT EXISTS attendancemarks (
    attendancemarkid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid text NOT NULL REFERENCES users(userid),
    classroomid text NOT NULL REFERENCES classrooms(id) ON UPDATE CASCADE,
    attendancedate date NOT NULL,
    status text NOT NULL CHECK (status IN ('present', 'absent')),
    source text NOT NULL CHECK (source IN ('legacy', 'student_checkin', 'teacher')),
    checkinat timestamptz,
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (userid, classroomid, attendancedate)
);
INSERT INTO attendancemarks (userid, classroomid, attendancedate, status, source)
SELECT ar.userid, ar.classroomid, dates.value::date, 'present', 'legacy'
FROM attendancerecords ar
CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(NULLIF(ar.presentdates, ''), '[]')::jsonb) dates(value)
ON CONFLICT (userid, classroomid, attendancedate) DO NOTHING;
INSERT INTO attendancemarks (userid, classroomid, attendancedate, status, source)
SELECT ar.userid, ar.classroomid, dates.value::date, 'absent', 'legacy'
FROM attendancerecords ar
CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(NULLIF(ar.absentdates, ''), '[]')::jsonb) dates(value)
ON CONFLICT (userid, classroomid, attendancedate) DO NOTHING;

CREATE TABLE IF NOT EXISTS attendancebatches (
    attendancebatchid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroomid text NOT NULL REFERENCES classrooms(id) ON UPDATE CASCADE,
    attendancedate date NOT NULL,
    version integer NOT NULL CHECK (version > 0),
    workflowstate text NOT NULL CHECK (workflowstate IN
        ('draft', 'approved', 'export_pending', 'exported', 'export_failed', 'correction_pending')),
    approvedby text REFERENCES users(userid),
    approvedat timestamptz,
    destinationconnectionid bigint REFERENCES integrationconnections(integrationconnectionid),
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (classroomid, attendancedate, version)
);
CREATE TABLE IF NOT EXISTS attendancebatchentries (
    attendancebatchentryid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendancebatchid bigint NOT NULL REFERENCES attendancebatches(attendancebatchid),
    userid text NOT NULL REFERENCES users(userid),
    status text NOT NULL CHECK (status IN ('present', 'absent')),
    attendancemarkid bigint REFERENCES attendancemarks(attendancemarkid),
    deliverystate text NOT NULL DEFAULT 'pending' CHECK
        (deliverystate IN ('pending', 'accepted', 'rejected', 'retry_pending')),
    externalrecordid text,
    lasterror text,
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (attendancebatchid, userid)
);
CREATE TABLE IF NOT EXISTS attendancedeliveryattempts (
    attendancedeliveryattemptid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendancebatchid bigint NOT NULL REFERENCES attendancebatches(attendancebatchid),
    integrationconnectionid bigint NOT NULL REFERENCES integrationconnections(integrationconnectionid),
    idempotencykey text NOT NULL UNIQUE,
    attemptnumber integer NOT NULL CHECK (attemptnumber > 0),
    state text NOT NULL CHECK (state IN ('started', 'accepted', 'rejected', 'retry_pending')),
    responsecode integer,
    errormessage text,
    startedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completedat timestamptz
);
CREATE TABLE IF NOT EXISTS integrationauditevents (
    integrationauditeventid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actoruserid text REFERENCES users(userid),
    eventtype text NOT NULL,
    entitytype text NOT NULL,
    entityid text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurredat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_externalentitymappings_sisid
    ON externalentitymappings (integrationconnectionid, entitykind, sisid) WHERE sisid IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_attendancemarks_class_date ON attendancemarks (classroomid, attendancedate);
CREATE INDEX IF NOT EXISTS ix_attendancebatches_state ON attendancebatches (workflowstate, updatedat);
CREATE INDEX IF NOT EXISTS ix_attendancedeliveryattempts_batch
    ON attendancedeliveryattempts (attendancebatchid, attemptnumber);

COMMIT;
